r=int(input("Enter the radius:"))
l=int(input("Enter the length:"))
b=int(input("Enter the breadth:"))
h=int(input("Enter the height:"))
Circarea =3.14*r*r
Rectarea=l*b
Triarea=0.5*b*h
print("Area of circle=",Circarea)
print("Area of Rectangle=",Rectarea)
print("Area of Triangle=",Triarea)
